channels:
    - conda-forge
dependencies:
    - python=3.7.*
    - numpy
    - pandas
    - xarray
    - matplotlib
    - cartopy
    - netcdf4
    - rioxarray
    - seaborn
    - geopandas
    - shapely
    - scipy